config/routes.rb
Rails.application.routes.draw do
  mount DmUniboCommon::Engine => "/dm_unibo_common", :as => "dm_unibo_common"

  get "/choose_organization", to: "home#choose_organization"

  scope ":__org__" do
    resources :users do
      resources :goods
      resources :good_requests
    end
    resources :documents
    resources :main_agreements do
      resources :documents
    end

    resources :goods do
      get "find", on: :collection
      post "find", on: :collection

      get "new_unload", on: :member
      post "unload", on: :member
      patch "unload", on: :member

      get "new_confirm", on: :member
      post "confirm", on: :member
      get "new_unconfirm", on: :member
      post "unconfirm", on: :member
      get "ask_category", on: :member
      post "set_category", on: :member

      get "print", on: :collection
    end

    resources :good_requests do
      put :approve, on: :member
      get :print, on: :member
    end

    resources :uploads

    resources :categories do
      resources :goods
      resources :good_requests
    end

    resources :locations

    resources :bookings

    # resources :servers do
    #   resources :bookings
    # end

    get "/hg/:id", to: "bookings#hg", as: :hg, defaults: {format: "json"}
    get "/", to: "goods#index", as: "current_organization_root"
  end

  root to: "goods#index"
end

app/models/good_request.rb
class GoodRequest < ApplicationRecord
  belongs_to :organization, optional: true
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  belongs_to :main_agreement, optional: true
  belongs_to :holder, class_name: 'User', foreign_key: :holder_id, optional: true

  attr_accessor :outside_agreements

  include AASM
  
  def to_s
    self.name
  end

  aasm do
    state :requested, initial: true
    state :holder_approved, :accepted, :ordered, :arrived

    event :holder_approve do 
      transitions from: :requested, to: :holder_approved
    end

    event :accept do
      transitions from: :holder_approved, to: :accepted
    end
  end
end

app/controllers/good_requests_controller.rb
class GoodRequestsController < ApplicationController
  before_action :set_good_request_and_check_permission, only: [:show, :edit, :update, :print, :destroy, :edit_approve, :approve]

  def index
    if policy(current_organization).manage?
      @good_requests = GoodRequest
    else
      @good_requests = current_user.good_requests
    end
    @good_requests = @good_requests.order('users.surname, users.name, category_id').includes(:category, :user)
    authorize :good_request
  end

  def new 
    @good_request = current_user.good_requests.new(organization: current_organization)

    if params[:category_id]
      @good_request.category = Category.find(params[:category_id])
      @available_agreements = @good_request.category.main_agreements.all 
    end

    if params[:main_agreement_id]
      @good_request.main_agreement = MainAgreement.find(params[:main_agreement_id]) 
      @good_request.name = @good_request.main_agreement.vendor_and_model
    end

    @good_request.outside_agreements = params[:outside_agreements]

    # se in convenzione o ha scelto fuori convenzione o se nella cateoria non ci sono convenzioni
    @can_ask = @good_request.main_agreement || @good_request.outside_agreements || (@good_request.category && @available_agreements.empty?) 

    authorize @good_request
  end

  def create
    @category = Category.find(params[:category_id])
    @good_request = @category.good_requests.new(good_request_params)

    @good_request.user = current_user unless policy(current_organization).manage?
    @good_request.organization = current_organization unless policy(current_organization).manage?

    authorize @good_request
    if @good_request.save
      redirect_to root_path, notice: "La richiesta è stata creato correttamente."
    else
      render action: :new, status: :unprocessable_entity
    end
  end

  def edit
    @good_request.outside_agreements = (! @good_request.main_agreement_id and @good_request.category.main_agreements.any?)
  end

  def update
    if @good_request.update(good_request_params)
      redirect_to root_path, notice: 'La richiesta è stata aggiornata.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def print
    filename = params[:man] ? 'manifestazione_esigenza_' : 'relazione_rup_'
    filename += @good_request.user.cn.gsub(' ', '_') + '.docx'
    respond_to do |format|
      format.docx do
        headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" 
        if params[:man]
          render 'good_requests/print_manifestazione'
        end
      end
    end
  end

  def destroy
    @good_request.destroy
    redirect_to root_path
  end

  def approve
    @good_request.holder_approve!
    redirect_to root_path
  end

  private

  def set_good_request_and_check_permission
    @good_request = GoodRequest.find(params[:id])
    authorize @good_request
  end

  def good_request_params
    p = [:category_id, :main_agreement_id, :holder_id, :name, :description, :teach_description, :derogation, :max_price]
    (p << :user_id) if policy(current_organization).manage?
    params[:good_request].permit(p)
  end
end

app/views/good_requests/_categories.html.erb
<h1>Si prega di scegliere la categoria</h1>
<div class="category-cards">
  <% Category.buyable.order(:number).find_each do |c| %>  
    <div class="card">
      <%= link_to new_category_good_request_path(c) do %>
        <button class="card-body btn btn-lg bt-info" style="width: 100%">
          <%= category_icon(c, size: 40)  %> 
          <br/><br/>
          <%= c.name.upcase %>
        </button>
      <% end %>
    </div>
  <% end %>
</div>

<div class="alert alert-warning">
  Per acquisti di altro tipo si prega di compilare....
</div>
.

app/views/good_requests/_form.html.erb
<% title = "Richiesta di #{current_user.cn} per #{@good_request.main_agreement ? @good_request.main_agreement.vendor_and_model : @good_request.category}" %>  

<% if @good_request.main_agreement %>  
  <%= render @good_request.main_agreement %>  
<% elsif @good_request.outside_agreements %>
  <div class="alert alert-danger">
    Nel caso nessuna convenzione soddisfi il fabbisogno specifico connesso, compilare la seguente richiesta:....
  </div>
<% else %>
  <div class="alert alert-warning">
    Tipologia: <%= @good_request.category %>. Non ci sono al momento convenzioni attive.
  </div>
<% end %>

<%= dm_form_for [@good_request.category, @good_request], title: title do |g| %>  
  <p>Io <%= current_user.cn %> richiedo di acquistare<br/>
    <% if @good_request.main_agreement %>  
      <%= @good_request.main_agreement.vendor_and_model %> in convenzione ``<%= @good_request.main_agreement.name %>''.  
    <% end %>
  </p>

  <% if policy(current_organization).manage? %>  
    <%= g.association :user, label_method: :cn_militar, include_blank: false %>  
  <% end %>
  <%= g.input :main_agreement_id, as: :hidden %>  
  <%= g.input :name %>  
  <%= g.input :teach_description, input_html: { rows: 2 } %>  
  <%= g.input :description, input_html: { rows: 4 } %>  
  <% if @good_request.outside_agreements  %>  
    <%= g.input :derogation, hint: 'Indicare il fabbisogno specifico per cui non è possibile acquistare il prodotto in adesione alle convenzioni. Indicare le caratteristiche essenziali mancanti ai prodotti in convenzione.', input_html: { rows: 6 } %>
  <% end %>
  <%= g.association :holder, label_method: :cn_militar, include_blank: false %>
  <%= g.input :max_price %>
  <%= g.submit %>
<% end %>

<div class="alert alert-warning mt-3">Esempi di interesse pubblico da soddisfare:
  <ul>
    <li>computer per lo svolgimento di attività di ricerca per il progetto _____</li>
    <li>computer per lo svolgimento di attività di didattica conseguente all’avvio di un nuovo corso di studio in _______</li>
    <li>servizio di manutenzione dello strumento X per il ripristino delle funzionalità ai fini dello svolgimento dell’ attività di didattica relativa al corso di studio in ______</li>
  </ul>
</div>

app/views/good_requests/_good_request.html.erb
<div class="card my-3">
  <div class="card-header">
    <strong>Richiesta di <%= good_request.user.cn.upcase %></strong>
    <span class="float-end">
      <% if good_request.main_agreement %>  
        in convenzione <%= good_request.main_agreement %>  
    <% else %>
      <span class="text-warning"> FUORI CONVENZIONE <%= dm_icon('exclamation-triangle') %></span>
    <% end %>
    </span>
  </div>
  <div class="card-body">
    <div style="text-weight: bold"><%= good_request.name %></div>
    <div style="font-style: italic; margin-left: 10px"><%= good_request.description %></div>
    <div style="font-style: italic; margin-left: 10px"><%= good_request.derogation %></div>
  </div>
  <div class="card-footer">
    <span class="font-italic">
      Prezzo massimo: <%= good_request.max_price %> &euro; su fondi di <%= good_request.holder %>
    </span>
    <% if good_request.holder_approved? %> 
      <span class="text-success">
        <%= dm_icon('check') %> (approvato)
      </span>
    <% end %>
    <span class="float-end">
      <% if policy(good_request).print? %>  
        <%= link_to dm_icon('print'), print_good_request_path(good_request, man: 1, format: :docx), title: 'Manifestazione Esigenza' %> 
        <%= link_to dm_icon('print'), print_good_request_path(good_request, rel: 1, format: :docx), title: 'Relazione Rup' %> 
      <% end %>
      <% if policy(good_request).edit? %>
        <%= link_to dm_icon('edit'), edit_good_request_path(good_request), title: 'Modifica richiesta' %> 
      <% end %>
      <% if policy(good_request).destroy? %>  
        <%= link_to_delete good_request_path(good_request) %> 
      <% end %>
      <% if policy(good_request).approve? %>  
        <% if good_request.holder_approved? %>  
          <%= dm_icon('check') %> 
        <% else %>
          <%= link_to dm_icon('check') + ' approva', approve_good_request_path(good_request), class: 'btn btn-success', method: :put %> 
        <% end %>
      <% end %>
    </span>
  </div>
</div>

app/views/good_requests/_main_agreements.html.erb
Sono disponibili le seguenti convenzioni attive da cui scegliere:  
<% @available_agreements.each do |ma| %>  
  <div>
    <%= render ma, with_button: true %>  
  </div>
<% end %>
<p>
Altrimenti, qualora le convenzioni attive [........]
</p>
<p>
<%= link_to dm_icon('plus', text: 'Richiedo di acquistare fuori dalle convenzioni'), new_category_good_request_path(@good_request.category, outside_agreements: 1), class: 'btn btn-danger' %>  
</p>

app/views/good_requests/index.html.erb
<h1>Nuove richieste di acquisto</h1>

<div>
  <% @good_requests.each do |gr| %>  
    <%= render gr %>  
  <% end %>
</div>

app/views/good_requests/new.html.erb
<% if @can_ask %>
  <%= render 'form' %>  
<% elsif @good_request.category %>
  <%= render 'good_requests/main_agreements' %>
<% else %>
  <%= render 'good_requests/categories' %>  
<% end %>