config/routes.rb
Rails.application.routes.draw do
  mount DmUniboCommon::Engine => "/dm_unibo_common", :as => "dm_unibo_common"

  get "/choose_organization", to: "home#choose_organization"

  scope ":__org__" do
    resources :users do
      resources :goods
      resources :good_requests
    end
    resources :documents
    resources :main_agreements do
      resources :documents
    end

    resources :goods do
      get "find", on: :collection
      post "find", on: :collection

      get "new_unload", on: :member
      post "unload", on: :member
      patch "unload", on: :member

      get "new_confirm", on: :member
      post "confirm", on: :member
      get "new_unconfirm", on: :member
      post "unconfirm", on: :member
      get "ask_category", on: :member
      post "set_category", on: :member

      get "print", on: :collection
    end

    resources :good_requests do
      put :approve, on: :member
      get :print, on: :member
    end

    resources :uploads

    resources :categories do
      resources :goods
      resources :good_requests
    end

    resources :locations

    resources :bookings

    # resources :servers do
    #   resources :bookings
    # end

    get "/hg/:id", to: "bookings#hg", as: :hg, defaults: {format: "json"}
    get "/", to: "goods#index", as: "current_organization_root"
  end

  root to: "goods#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    authorize :home
    if current_organization 
      @good_requests = current_user.good_requests.all
      @good_requests_as_holder = GoodRequest.where(holder_id: current_user.id).all
      @good_requests_as_holder -= @good_requests 
    else
      redirect_to choose_organization_path and return
    end
  end

  def choose_organization
    authorize :home
    if current_user_has_some_authorization?
      @organizations = current_user.my_organizations
    else
      @organizations = current_user.goods.group(:organization_id).map(&:organization)
    end

    if @organizations.size == 1 
      redirect_to current_organization_root_path(__org__: @organizations.first.code)
    end
  end
end

app/views/home/choose_organization.html.erb
<% if @organizations.any? %>  
  <h1>Scegli la tua struttura</h1>

  <div class="row">
    <% @organizations.each do |o| %>  
      <div class="col-md-6">
        <%= link_to o.name, o.code, class: 'btn btn-lg btn-primary w-100 h-100' %>
      </div>
    <% end %>
  </div>
<% else %>
  <h2 class="text-center p-5 m-5 alert alert-danger">No avete accesso a nessuna struttura.</h2>
  <p>Si prega di contattare <%= support_mail %></p>
<% end %>

app/views/home/index.html.erb
<h1>Gestione risorse e materiale inventariabile<br/><small><%= current_organization.name %></small></h1>

<% @good_requests.each do |gr| %>  
  <%= render gr %>  
<% end %>

<% if @good_requests_as_holder.any? %>  
  <h2>Richieste sui suoi fondi</h2>
  <% @good_requests_as_holder.each do |gr| %>
    <%= render gr %>
  <% end %>
<% end %>

<div style="text-align: center">
  <div class="my-3">
    <%= link_to new_good_request_path do %>
      <button class="btn btn-lg btn-info py-3" style="width: 75%; font-size: 200%">
        <%= dm_icon('plus', size: "2xl") %> <br/> NUOVA <br/>RICHIESTA DI ACQUISTO
      </button>
    <% end %>
  </div>

  <div class="my-3">
    <%= link_to goods_path do %>
      <button class="btn btn-lg btn-info py-3" style="width: 75%; font-size: 200%">
        <%= dm_icon('search', size: "2xl") %> <br/> PROPRIA <br/>SITUAZIONE INVENTARIALE
      </button> 
    <% end %>
  </div>
</div>