config/routes.rb
Rails.application.routes.draw do
  mount DmUniboCommon::Engine => "/dm_unibo_common", :as => "dm_unibo_common"

  get "/choose_organization", to: "home#choose_organization"

  scope ":__org__" do
    resources :users do
      resources :goods
      resources :good_requests
    end
    resources :documents
    resources :main_agreements do
      resources :documents
    end

    resources :goods do
      get "find", on: :collection
      post "find", on: :collection

      get "new_unload", on: :member
      post "unload", on: :member
      patch "unload", on: :member

      get "new_confirm", on: :member
      post "confirm", on: :member
      get "new_unconfirm", on: :member
      post "unconfirm", on: :member
      get "ask_category", on: :member
      post "set_category", on: :member

      get "print", on: :collection
    end

    resources :good_requests do
      put :approve, on: :member
      get :print, on: :member
    end

    resources :uploads

    resources :categories do
      resources :goods
      resources :good_requests
    end

    resources :locations

    resources :bookings

    # resources :servers do
    #   resources :bookings
    # end

    get "/hg/:id", to: "bookings#hg", as: :hg, defaults: {format: "json"}
    get "/", to: "goods#index", as: "current_organization_root"
  end

  root to: "goods#index"
end

app/models/good.rb
class Good < ApplicationRecord
  include AASM

  belongs_to :organization
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  belongs_to :location, optional: true

  validates :inv_number, uniqueness: {}
  # validates :name, presence: {}

  validate  :validate_user_upn

  #aasm do
  #  state :sleeping, initial: true
  #end

  def to_s
    self.name
  end

  def user_upn
    self.user_id ? self.user.upn : nil
  end

  def user_upn=(upn)
    Rails.logger.info("method user_upn= with upn=#{upn}")
    if upn =~ /(\w+\.\w+@unibo.it)/ 
      @_user_upn = $1
    else
      @_user_upn = upn
    end
  end

  def validate_user_upn
    Rails.logger.info("validating user_upn=#{@_user_upn}")

    return true if @_user_upn.blank?

    u = User.find_by_upn(@_user_upn)

    if u
      Rails.logger.info("validate_user_upn: found #{@_user_upn} -> #{u.inspect}")
      self.user_id = u.id
    end
  end
 
  # we want the user to confirm every year
  def better_to_confirm
    ! (self.confirmed && (((Time.zone.now - self.confirmed).to_i / 86400) < 365))
  end

  def confirm_presence(user)
    self.update(confirmed: Time.now, confirmed_by: user.id, unconfirmed: nil)
  end

  def unconfirm_presence(motivation)
    self.update(confirmed: nil, confirmed_by: nil, unconfirmed: Time.now, unconfirmed_text: motivation)
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good_and_check_permission, only: [:show, :edit, :update, :new_unload, :unload, :new_confirm, :confirm, :new_unconfirm, :unconfirm, :ask_category, :set_category]

  def index
    @goods = current_organization.goods.includes(:category, :user, :location)

    if policy(current_organization).read?
      if params[:unassigned]
        @goods = @goods.where(user_id: nil)
        @title = "Elenco beni non assegnati"
      elsif params[:unconfirmed]
        @goods = @goods.where.not(unconfirmed: nil)
        @title = "Elenco beni dichiarati non posseduti."
      elsif params[:no_category]
        @goods = @goods.where(category_id: nil).order(:description)
        @title = "Elenco beni senza categoria"
      elsif params[:user_id]
        @user  = User.find(params[:user_id])
        @goods = @goods.where(user_id: @user.id)
        @title = "Elenco beni #{@user}"
      elsif params[:category_id]
        @category = Category.find(params[:category_id])
        @goods = @goods.where(category_id: @category.id)
        @title = "Elenco beni tipo \"#{@category}\""
        @no_icon = true
      elsif params[:location_id] && params[:location_id] != "0"
        @location = Location.find(params[:location_id])
        @goods = @goods.where(location_id: @location.id)
        @title = "Elenco beni presso \"#{@location}\""
      elsif params[:location_id] == "0"
        @goods = @goods.where(location_id: nil)
        @title = "Elenco beni senza ubicazione"
      elsif params[:unload]
        @goods = @goods.where(to_unload: true).order(:build_year)
        @title = "Elenco beni da disinventariare"
      elsif params[:newer]
        @goods = @goods.where("created_at > ?", params[:newer].to_i.days.ago)
        @title = "Elenco ultimi inserimenti"
      else
        @goods = @goods.where(user_id: nil)
        @title = "Elenco beni non assegnati"
      end
    else
      @title = "Elenco beni a lei assegnati"
      @goods = @goods.where(user_id: current_user.id).where(to_unload: nil)
    end
    authorize :good
  end

  def edit
  end

  def update
    manage_confirmed_param
    if @good.update(good_params)
      # redirect_to good_path(@good), notice: "Aggiornamento registrato correttamente."
    else
      render action: :show, status: :unprocessable_entity
    end
  end

  def find
    authorize current_organization, :read?
    @search_string = params[:search_string] || ""
    @title = "Ricerca per #{@search_string}"

    @goods = []

    # first by inv num
    if @search_string.match?(/\A[0-9]+\Z/)
      @goods << current_organization.goods.where(inv_number: @search_string.to_i).to_a
      @goods << current_organization.goods.where(old_inv_number: @search_string.to_i).to_a
    end
    if @search_string.size > 2
      sql_string = "%#{@search_string}%"
      @goods << current_organization.goods.where("goods.description like ? or goods.unibo_description like ? or goods.sn like ?", sql_string, sql_string, sql_string).to_a
    end

    @goods.flatten!
    render action: :index
  end

  def new_unload
  end

  def unload
    if @good.to_unload
      @good.update(to_unload: false, to_unload_status: nil)
    else
      @good.update(to_unload: true, to_unload_status: params[:good][:to_unload_status])
    end
  end

  def new_confirm
  end

  # only simple users
  def confirm
    @good.confirm_presence(current_user)
    redirect_to goods_path
  end

  def new_unconfirm
  end

  def unconfirm
    @good.unconfirm_presence(params[:unconfirm][:motivation])
    redirect_to goods_path
  end

  def ask_category
    render layout: false
  end

  def set_category
    @good.update_attribute(:category_id, params[:category_id])
    @good.reload
  end

  def print
    authorize :good
    @goods = Good.where(to_unload: true).select(:inv_number, :unibo_description, :to_unload_status).to_a
    respond_to do |format|
      format.html { render layout: false }
      format.csv do
        header = ["Inv.", "Descrizione", "Stato"].to_csv
        data = @goods.map { |x| [x.inv_number, x.unibo_description, x.to_unload_status].to_csv }.join
        filename = "Richiesta_scarichi_#{I18n.l Date.today}_#{current_organization.name}.csv"
        send_data header + data, filename: filename
      end
    end
  end

  private

  def set_good_and_check_permission
    @good = Good.find(params[:id])
    authorize @good
  end

  # FIXME how to unconfirm
  def manage_confirmed_param
    # confirmed in database is datetime and in form is just bool
    if policy(@good).confirm?
      if params[:good].delete(:confirmed) == "1"
        @good.confirm_presence(current_user)
      end
    end
  end

  def good_params
    params[:good].permit(:name, :description, :user_request, :category_id, :user_upn, :location_id, :confirmed, :admin_notes, :to_unload_status)
  end
end

app/helpers/goods_helper.rb
module GoodsHelper

  def old_inv_number(good, found: nil)
    return "" unless good.old_inv_number 
    content_tag :span, class: "old_inv_number p-1 #{'found' if found}" do
      "#{good.old_inv_number.to_i} - #{good.old_org}"
    end
  end

  def link_to_unload(good)
    return "" unless helpers.policy(good).unload?

    icon = good.to_unload ? dm_icon("times-circle") : dm_icon("trash-alt")
    title = good.to_unload ? "cancella lo scarico" : "da scaricare"
    confirm = good.to_unload ? "Sicuri di volere cancella lo scarico?" : "Sicuri vi volere scaricare il materiale?"
    if good.to_unload
      button_to icon, unload_good_path(good), title: title, form: {data: {"turbo-confirm": confirm}, class: "d-inline px-0 mx-0"}
    else
      link_to icon, new_unload_good_path(good, modal: 1), title: title, data: {turbo_frame: :modal} 
    end
  end

  def status_icon(good, size: 20)
    if good.unconfirmed
      "<i class='fas fa-exclamation-triangle text-danger' style='font-size: #{size}px' title='presenza del bene non confermata'></i>".html_safe
    elsif good.confirmed
      "<i class='fas fa-check-circle text-success' style='font-size: #{size}px' title='presenza del bene confermata'></i>".html_safe
    else
      ""
    end
  end

  def description_for_owner(good)
    "#{good.name} #{good.description} (descrizione originale in u-gov: #{good.unibo_description})  "
  end
end

app/views/goods/_categories_list.html.erb
<div class="list-group list-group-flush">
  <% Category.find_each do |c| %>
    <%= link_to c, set_category_good_path(@good, category_id: c.id), method: :put, remote: true, class: "list-group-item list-group-item-action m-0" %>
  <% end %>
</div>

app/views/goods/_form.html.erb
<%= dm_form_for @good do |f| %>  
  <%= f.input :inv_number, disabled: true, as: :string %>  
  <%= f.input :name %>  
  <%= f.input :description, input_html: {rows: 4} %>  
  <%= f.input :user_upn %>
  <%= f.association :category %>
  <%= f.association :location %>

  <%= f.input :admin_notes, as: :string %>  

  <% confirmed_hint = @good.confirmed ? "Ultima conferma di presenza: #{I18n.l(@good.confirmed)} da #{User.find(@good.confirmed_by)}. Fare check per confermare nuovamente" : "Fare check per confermare la presenza" %>  
  <%= f.input :confirmed, as: :boolean, input_html: { checked: false }, hint: confirmed_hint %>

  <%= f.input :to_unload_status %>  

  <%= f.submit %>  
<% end %>

<div class="alert alert-warning">
  in Ugov:<br/>
  <strong>sn:</strong><%= @good.sn %><br/>
  <strong>Descrizione:</strong><i><%= @good.unibo_description %></i><br/>
</div>

<%= javascript_tag do  %>  
  <%= render partial: "dsausers/awesomplete", formats: :js %>  
<% end %>

app/views/goods/ask_category.html.erb
<%= render DmUniboCommon::ModalComponent.new() do %>
  <h2>Scegli la categoria di appartenenza</h2>
  <div class="list-group list-group-flush">
    <% Category.find_each do |c| %>
      <%= button_to c, set_category_good_path(@good, category_id: c.id), class: "list-group-item list-group-item-action m-0" %>
    <% end %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<% if modal_page %>  
  <%= render DmUniboCommon::ModalComponent.new() do %>
    <%= render 'form' %>
  <% end %>
<% else %>
  <%= render 'form' %>
<% end %>

app/views/goods/edit.turbo_stream.erb
<%= render DmUniboCommon::ModalComponent.new() do %>
  <h1>CIAO</h1>
<% end %>

app/views/goods/index.html.erb
<h1>
  <span class="mr-5"><%= category_icon(@category, size: 40) if @category %></span> 
  <%= @title %>
</h1>

<div>
  <% @goods.each do |good| %>  
    <%= render Good::CardComponent.new(good, current_user, no_icon: @no_icon, search_string: @search_string) %>  
  <% end %>
</div>

app/views/goods/new.html.erb
<%= render partial: 'form' %>  

app/views/goods/new_confirm.html.erb
<div class="alert alert-info">
  <p>Da questa pagina può segnalare che l'oggetto con numero di inventario <strong><%= @good.inv_number %></strong></p>
  <p class="m-3 font-weight-bold"><%= description_for_owner(@good) %></p>
  <p>risulta in suo possesso.</p>
</div>

<div class="centered">
  <%= form_tag confirm_good_path(@good) do %>  
    <%= submit_tag "CONFERMO CHE IL BENE È IN MIO POSSESSO", class: 'btn-lg p-3' %> - <%= link_to_back goods_path %>  
  <% end %>
</div>

app/views/goods/new_unconfirm.html.erb
<div class="alert alert-info">
  <p>Da questa pagina può segnalare che l'oggetto</p>
  <p class="m-3 font-weight-bold"><%= description_for_owner(@good) %></p>
  <p>non risulta più in suo possesso.</p>
</div>

<%= simple_form_for :unconfirm, url: unconfirm_good_path(@good) do |f| %>  
  <%= f.input :motivation, label: 'Messaggio', as: :text, required: false, hint: "Per completare la segnalazione si prega di compilare questo campo fornendo quante più informazioni disponibili per aiutare a determinare l'attuale posizione del bene."%> 
  <%= f.submit 'Invia segnalazione' %> - <%= link_to_back goods_path %>  
<% end %>

app/views/goods/new_unload.html.erb
<%= render DmUniboCommon::ModalComponent.new() do %>
  <%= dm_form_for @good, url: [:unload, @good], title: 'Motivazione per disinventario e stato del bene' do |f| %>  
    <%= f.input :to_unload_status, label: 'Note'.html_safe %>  
    <%= f.submit 'Salva' %>  
  <% end %>
<% end %>

app/views/goods/set_category.js.erb
$("#<%= div_good_id(@good) %> .category_icon").popover('hide');
$("#<%= div_good_id(@good) %> .category_icon").html("<%= category_icon(@good.category) %>");

app/views/goods/set_category.turbo_stream.erb
<%= turbo_stream.replace dom_id(@good) do %>  
  <%= render Good::CardComponent.new(@good, current_user) %>  
<% end %>

app/views/goods/show.html.erb
<%= render Good::CardComponent.new(@good, current_user) %>  

app/views/goods/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@good)}" do %>
  <%= render Good::CardComponent.new(@good, current_user, no_icon: @no_icon, search_string: @search_string) %>  
<% end %>