config/routes.rb
Rails.application.routes.draw do
  mount DmUniboCommon::Engine => "/dm_unibo_common", :as => "dm_unibo_common"

  get "/choose_organization", to: "home#choose_organization"

  scope ":__org__" do
    resources :users do
      resources :goods
      resources :good_requests
    end
    resources :documents
    resources :main_agreements do
      resources :documents
    end

    resources :goods do
      get "find", on: :collection
      post "find", on: :collection

      get "new_unload", on: :member
      post "unload", on: :member
      patch "unload", on: :member

      get "new_confirm", on: :member
      post "confirm", on: :member
      get "new_unconfirm", on: :member
      post "unconfirm", on: :member
      get "ask_category", on: :member
      post "set_category", on: :member

      get "print", on: :collection
    end

    resources :good_requests do
      put :approve, on: :member
      get :print, on: :member
    end

    resources :uploads

    resources :categories do
      resources :goods
      resources :good_requests
    end

    resources :locations

    resources :bookings

    # resources :servers do
    #   resources :bookings
    # end

    get "/hg/:id", to: "bookings#hg", as: :hg, defaults: {format: "json"}
    get "/", to: "goods#index", as: "current_organization_root"
  end

  root to: "goods#index"
end

app/models/main_agreement.rb
class MainAgreement < ApplicationRecord
  belongs_to :organization
  belongs_to :category
  has_many   :documents
  has_many   :good_requests

  def to_s
    self.title
  end
end

app/controllers/main_agreements_controller.rb
class MainAgreementsController < ApplicationController
  before_action :set_main_agreement_and_check_permission, only: [:show, :edit, :update, :destroy]

  def index
    @main_agreements = current_organization.main_agreements.order(:category_id, :price).includes(:category, :good_requests).all
    authorize :main_agreement
  end

  def new
    @main_agreement = current_organization.main_agreements.new
    authorize @main_agreement
  end

  def create
    @main_agreement = current_organization.main_agreements.new(main_agreement_params)
    authorize @main_agreement
    if @main_agreement.save
      redirect_to main_agreements_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @main_agreement.update(main_agreement_params)
      redirect_to main_agreements_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @good_requests = @main_agreement.good_requests.all
    if @good_requests.any?
      redirect_to good_requests_path
    else
      @main_agreement.destroy
      redirect_to main_agreements_path
    end
  end

  private

  def main_agreement_params
    params[:main_agreement].permit(:category_id, :title, :name, :vendor_and_model, :description, :notes, :price, :document)
  end

  def set_main_agreement_and_check_permission
    @main_agreement = MainAgreement.find(params[:id])
    authorize @main_agreement
  end
end

app/helpers/main_agreements_helper.rb
module MainAgreementsHelper
  def main_agreement_description(ma)
    ma.split(';').map do |line|
      (n, v) = line.split('#')
      "<strong>#{h n}</strong>: #{h v}".html_safe
    end.join('<br/>').html_safe
  end
end

app/views/main_agreements/_form.html.erb
<% documents = @main_agreement.documents.all %>  

<%= dm_form_for @main_agreement do |ma| %>  
  <%= ma.association :category, include_blank: false %>  
  <%= ma.input :title %>  
  <%= ma.input :name %>  
  <%= ma.input :code %>  
  <%= ma.input :vendor_and_model %>  
  <%= ma.input :description, input_html: { rows: 6 } %>  
  <%= ma.input :notes %>  
  <%= ma.input :price %>  

  <%= ma.submit %>  
<% end %>

<% if documents.any? %>  
  <h5> Allegati</h5>
  <ul class="list-group">
    <% documents.each do |doc| %>  
      <li class="list-group-item">
        <%= link_to doc.name, doc.attach %> 
        <span class="float-end">
          <%= link_to_delete "", doc %>
          <%= link_to_edit "", edit_document_path(doc) %>
        </span>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/main_agreements/_main_agreement.html.erb
<div class="card my-3">  
  <div class="card-header font-weight-bold">
    <%= category_icon main_agreement.category %> <%= main_agreement.name %>  
    <% if policy(main_agreement).edit? %>  
      <span class="float-end"><%= link_to_edit [:edit, main_agreement] %></span>
    <% end %>
  </div>
  <div class="card-body">
    <div class="font-weight-bold mb-3">
      <%= main_agreement.vendor_and_model.upcase %> 
      <span class="float-end badge bg-pill bg-warning" style="font-size: 110%">
        <%= main_agreement.price %> &euro; + iva
      </span>
    </div>
    <% unless main_agreement.description.blank? %>  
        <%= main_agreement_description(main_agreement.description) %>  
    <% end %>
    <% unless main_agreement.notes.blank? %>  
      <strong>note:</strong> <%= main_agreement.notes %><br/>
    <% end %>
    <% main_agreement.documents.each do |doc| %>  
      <p class="my-1"><strong>Allegato:</strong>  <%= link_to doc.name, doc.attach %></p>
    <% end %>
  </div>
  <% if defined?(with_button) and with_button == true %>  
    <div class="card-footer">
      <%= link_to dm_icon('plus', text: 'Scelgo questa convenzione'), new_category_good_request_path(main_agreement.category, main_agreement_id: main_agreement.id), class: 'btn btn-success' %>
      <% if policy(main_agreement).edit? %>  
        <%= link_to dm_icon('file', text: 'Allega documento'), new_main_agreement_document_path(main_agreement), class: 'btn btn-primary' %>  
        <%= link_to dm_icon('edit', text: 'Modifica'), edit_main_agreement_path(main_agreement), class: 'btn btn-primary' %>  
        <%= link_to dm_icon('trash', text: 'Elimina la Convenzione'), main_agreement_path(main_agreement), method: :delete, title: 'elimina', data: {confirm: 'Siete sicuri di voler cancellare?'}, class: 'btn btn-danger' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/main_agreements/edit.html.erb
<%= render 'form' %>  

app/views/main_agreements/index.html.erb
<h1>Convenzioni</h1>

<% @main_agreements.each do |ma| %>  
  <%= render ma, with_button: true %>  
  <div class="list-group">
  <% ma.good_requests.each do |gr| %>  
    <div class="list-group-item list-group-item-success"><%= gr.user.cn %>: <%= link_to gr, [:edit, gr] %></div>
  <% end %>
  </div>
<% end %>

<% if policy(current_organization).manage? %>  
  <p class="m-3">
  <%= link_to 'NUOVA CONVENZIONE', new_main_agreement_path, class: 'btn btn-primary' %>  
  </p>
<% end %>

app/views/main_agreements/new.html.erb
<h1>Nuova convenzione</h1>

<%= render 'form' %>  